version: "3.9"
services:
    urlibrary-api:
        container_name: urlibrary-api
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/app
            - ./docker/php/php.ini://usr/local/etc/php/php.ini
        environment:
            - TZ=Asia/Tokyo

    urlibrary-nginx:
        image: nginx
        container_name: nginx
        ports:
            - ${NGINX_PORT:-8080}:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - urlibrary-api

    urlibrary-db:
        image: mysql:8.0
        container_name: urlibrary-db
        volumes:
            - ./docker/db/data:/var/lib/mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
            - MYSQL_DATABASE=urlibrary
            - MYSQL_USER=urlibrary
            - MYSQL_PASSWORD=urlibrary
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Tokyo
        ports:
            - ${DB_PORT-3306}:3306

    urlibrary-db-testing:
        image: mysql:8.0
        container_name: urlibrary-db-testing
        tmpfs:
            - /var/lib/mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
            - MYSQL_DATABASE=urlibrary
            - MYSQL_USER=urlibrary
            - MYSQL_PASSWORD=urlibrary
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Tokyo
        ports:
            - 3307:3306

    urlibrary-mailcatcher:
        image: schickling/mailcatcher
        container_name: urlibrary-mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
