services:
  - type: web
    name: urlibrary-api
    env: docker
    plan: free
    branch: develop
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    preDeployCommand: |
      php artisan optimize
      php artisan migrate --force
