name: Deploy to Fly.io

on:
  push:
    branches: [main]
    paths: ["api/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --wait-timeout 300
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run Database Migrations
        run: flyctl ssh console --command "php artisan migrate --force"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Clear Application Cache
        run: flyctl ssh console --command "php artisan cache:clear && php artisan config:cache && php artisan route:cache"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
